### PR TITLE
Update ms graph android sdk to java sdk

### PR DESCRIPTION
**Pull request by vikyding**
Update MSGraphServiceClientManager class
Update MSGraphServiceController class

### CODE REVIEW

**Comment by vikyding** [comment]
@deepak2016 @jthake-msft Please review the pr for the update and pull in. Thanks

**Comment by jthake-msft** [comment]
Each training repo actually has a completed project with it as well. For the PR to be approved, you would need to submit the PR with those changes also. I would actually just pull down the repo and run that completed project to validate this works ok, rather than follow the lab steps.

**Comment by vikyding** [comment]
@jthake-msft  Sorry for missing code file changes. But it seems that I didn't have write permission to this repo, my push failed with the permission denied. Could you add write permission for me?

**Comment by jthake-msft** [comment]
The way we do this is via submitting PRs. We do not need to grant permissions directly to the repo. If you reject your own PR and then submit a new PR with the branch with the completed project folder location that would be great!

**Pull request closed without merging**
