### PR TITLE
FY2019Q4 Quarterly refresh

### PR DESCRIPTION
**Pull request by andrewconnell**
- validated tutorial steps (made lots of changes)
- updated tutorial file names to be ordered
- updated tutorial steps to match same bullet-list format as other training modules
- updated screenshots
- updated code downloads
- fixed / updated code issues in tutorial

### CODE REVIEW

**Comment by jasonjoh** [comment]
I haven't looked at the code stuff yet, but in the Markdown I've got some big objections to the changes :).

- Renaming the files breaks our docs publication, requiring me to go do some manual updates. Can we not do that?
- Converting the topics to numbered lists is not consistent with how we publish stuff on Docs. The Docs folks actually tell us explicitly NOT to do that. We need to revert that change.

**Comment by jasonjoh** [comment]
On the code front I'm guessing the changes are massive because of recreating the project with latest Android Studio?

**Comment by andrewconnell** [comment]
@jasonjoh said:
> On the code front I'm guessing the changes are massive because of recreating the project with latest Android Studio?

There were a lot of code changes as the tutorial as is didn't work for me. I don't think there was much different with the Andriod Studio update, rather the majority of the changes were just differences in copy/paste.

@jasonjoh said:
> Renaming the files breaks our docs publication, requiring me to go do some manual updates. Can we not do that?

OK... I'll undo that and put it the way it was

@jasonjoh said:
> Converting the topics to numbered lists is not consistent with how we publish stuff on Docs. The Docs folks actually tell us explicitly NOT to do that. We need to revert that change.

I'll need to check on this as this doesn't match the way the other modules work that are done for OfficeDev. The format they were in is generally considered non-condusive to learning (prose-style steps rather than real steps). I'll follow up...

**Comment by andrewconnell** [comment]
@jasonjoh Apparently the default `.gitingore` in the root of the repo is incorrect in that it included MORE files that were necessary for an Andriod Studio project... basically everything in `.gradle` & `.idea`. It assumed they'd be in the root... but they aren't in a content repo like this. I'm not sure when that changed but it hadn't done that in previous quarterly refreshes.

I'll submit a commit that cleans that up and removes a lot of files...

**Comment by andrewconnell** [comment]
@jasonjoh the number of files changed appears to be the effect of the refresh using the latest version of Android Studio. Appears the `.gitignore` files are different than what was put there originally. Suspect some hand-edits were done to the project files when this module was ported over from its previous configuration. The other stuff appears to be whitespace changes... again... I don't do any config changes to Andriod Studio, just take the default setup.

**Comment by jasonjoh** [comment]
Per our email discussion I'm going to merge this into a testing branch for now so we can evaluate the formatting changes and see if we want to adopt them across all of our tutorials.

**Pull request merged**
